Add conda installation to docs
mdolab/CMPLXFOIL pull request #20
Opened 2022-10-17 01:14 UTC by A-CGray

## Purpose

Now that CMPLXFOIL can be installed with conda I added a section explaining this in the docs

## Expected time until merged

3 seconds

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing

## Checklist

- [ ] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation

2022-10-17 01:18 UTC, bernardopacini submitted a review, later dismissed
LGTM, thanks @A-CGray!

2022-10-17 01:29 UTC, eytanadler reviewed
Thanks for the update! What do you think about adding the line “conda install -c conda-forge cmplxfoil” directly into our docs (and maybe saying it supports Linux and macOS) to avoid another click? Sorry this review is a little late since it’s not within 3 sec.

2022-10-17 02:00 UTC, A-CGray commented
> Thanks for the update! What do you think about adding the line “conda install -c conda-forge cmplxfoil” directly into our docs (and maybe saying it supports Linux and macOS) to avoid another click? Sorry this review is a little late since it’s not within 3 sec.

Could do, I thought I'd just link to the official conda forge page so we didn't have to worry about keeping something in our docs up to date with the correct installation instructions there, but maybe there is very little chance of the installation command changing?

2022-10-17 14:07 UTC, eytanadler requested changes

2022-10-17 14:07 UTC, eytanadler commented on doc/install.rst
> +Conda Installation
Also just noticed, could you add
```
************
Installation
************
```
at the top of this page so it appears as a single entry in the left sidebar in the docs?

2022-10-17 14:37 UTC, eytanadler approved these changes
LGTM!

2022-10-21 14:57 UTC, A-CGray commented
Bump @bernardopacini

2022-10-21 16:21 UTC, bernardopacini approved these changes
Eek sorry, didn't realize my approval had been dismissed. Looks good to me.

2022-10-21 16:22 UTC, merged